spring.application.name=chapter6

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/hsf302_ch6
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
